#!/bin/bash

export HOSTNAME=$(hostname)
bash color.sh "HOSTNAME =" "$HOSTNAME"
export TIMEZONE="$(cat /etc/timezone) UTC $(date +"%Z")"
bash color.sh "TIMEZONE =" "$TIMEZONE"
export USER="$USER"
bash color.sh "USER =" "$USER"
export OS="$(lsb_release -a | awk '/Description/ {for (i=3; i<=NF; i++) printf "%s ", $i}')"
bash color.sh "OS =" "$OS"
export DATE="$(date +"$d %b %Y %T")"
bash color.sh "DATE =" "$DATE"
export UPTIME="$(uptime -p)"
bash color.sh "UPTIME =" "$UPTIME"
export UPTIME_SEC="$(cat /proc/uptime | awk '{printf($1)}')"
bash color.sh "UPTIME_SEC =" "$UPTIME_SEC"
export IP="$(hostname -I | awk '{printf($1)}')"
bash color.sh "IP =" "$IP"
export MASK="$(ifconfig $(ip r | grep default | awk '{printf($5)}') | awk '/netmask / {printf($4)}')"
bash color.sh "MASK =" "$MASK"
export GATEWAY="$(ip r | grep default | awk '{printf($3)}')"
bash color.sh "GATEWAY= " "$GATEWAY"
export RAM_TOTAL="$(free | grep -e Mem: | awk '{printf("%.3f", $2/(1024 * 1024))}') "Gb""
bash color.sh "RAM_TOTAL= " "$RAM_TOTAL"
export RAM_USED="$(free | grep -e Mem:| awk '{printf("%.3f", $3/(1024*1024))}') "Gb""
bash color.sh "RAM_USED =" "$RAM_USED"
export RAM_FREE="$(free | grep -e Mem:| awk '{printf("%.3f", $4/(1024*1024))}') "Gb""
bash color.sh "RAM_FREE =" "$RAM_FREE"
export SPACE_ROOT="$(df /| grep dev | awk '{printf("%.2f", $2/1024)}') "Mb""
bash color.sh "SPACE_ROOT =" "$SPACE_ROOT"
export SPACE_ROOT_USED="$(df / | grep dev | awk '{printf("%.2f", $3/1024)}') "Mb""
bash color.sh "SPACE_ROOT_USED= " "$SPACE_ROOT_USED"
export SPACE_ROOT_FREE="$(df / | grep dev | awk '{printf("%.2f", $4/1024)}') "Mb""
bash color.sh "SPACE_ROOT_FREE =" "$SPACE_ROOT_FREE"

